# Generated by Django 4.2.29 on 2026-04-08 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-period_start', '-period_end'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='month',
            new_name='period_end',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='period_start',
            field=models.DateField(default=datetime.datetime(2026, 4, 8, 1, 10, 2, 804654, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'period_start', 'period_end')},
        ),
    ]
