# Generated by Django 4.2.29 on 2026-04-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-period_start', '-period_end']},
        ),
    ]
