# Generated by Django 4.2.29 on 2026-04-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(unique=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='e.g. Christmas every year')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
