# Generated by Django 4.2.29 on 2026-04-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_holiday_options_attendance_overtime_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='holiday_worked',
            field=models.PositiveIntegerField(default=0, help_text='Number of holidays worked during this period'),
        ),
    ]
