# Generated by Django 4.2.29 on 2026-04-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payroll_overtime_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='holiday_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
